# Generated by Django 4.1.2 on 2022-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_discount',
            field=models.FloatField(default=1.0),
        ),
    ]
