# Generated by Django 4.1.2 on 2022-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_product_p_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='p_discount',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
